
ALTER TABLE public.aut_courses DROP CONSTRAINT IF EXISTS aut_courses_category_check;
ALTER TABLE public.aut_courses ADD CONSTRAINT aut_courses_category_check
  CHECK (category IN ('university_required','university_elective','college_required','department_required','department_elective','remedial'));

DELETE FROM public.equivalency_matches WHERE aut_course_id IS NOT NULL;
DELETE FROM public.aut_courses;

INSERT INTO public.aut_courses (course_code, course_name_ar, course_name_en, credits, category, display_order, is_active) VALUES
('2110104','مهارات الاتصال والتواصل باللغة العربية (1)','Arabic Communication Skills (1)',2,'university_required',1,true),
('2110106','مهارات الاتصال والتواصل باللغة الإنجليزية (1)','English Communication Skills (1)',2,'university_required',2,true),
('2110108','التربية الوطنية','National Education',2,'university_required',3,true),
('2110109','العلوم العسكرية','Military Sciences',3,'university_required',4,true),
('2110115','الريادة والابتكار','Entrepreneurship and Innovation',2,'university_required',5,true),
('2110117','القيادة والمسؤولية المجتمعية','Leadership and Social Responsibility',2,'university_required',6,true),
('2110120','مهارات حياتية','Life Skills',2,'university_required',7,true),
('2110105','مهارات الاتصال والتواصل باللغة العربية (2)','Arabic Communication Skills (2)',3,'university_elective',10,true),
('2110107','مهارات الاتصال والتواصل باللغة الإنجليزية (2)','English Communication Skills (2)',3,'university_elective',11,true),
('2110110','الإسعافات الأولية والسلامة العامة','First Aid and General Safety',3,'university_elective',12,true),
('2110111','التجارة الإلكترونية','E-Commerce',3,'university_elective',13,true),
('2110112','التنمية والبيئة','Development and Environment',3,'university_elective',14,true),
('2110113','الثقافة الرقمية','Digital Culture',3,'university_elective',15,true),
('2110114','الحضارة الإسلامية','Islamic Civilization',3,'university_elective',16,true),
('2110116','الغذاء والدواء','Food and Drugs',3,'university_elective',17,true),
('2110118','تعلم التفكير المنطقي','Logical Thinking',3,'university_elective',18,true),
('2110119','حقوق الملكية الفكرية','Intellectual Property Rights',3,'university_elective',19,true),
('2110121','الإحصاء والاحتمالات لطلبة تكنولوجيا المعلومات','Statistics and Probability for IT',3,'college_required',30,true),
('2110122','تفاضل وتكامل (1)','Calculus (1)',3,'college_required',31,true),
('2110137','اللغة الإنجليزية المتخصصة لطلبة تكنولوجيا المعلومات','Specialized English for IT',3,'college_required',32,true),
('2110138','مقدمة في البرمجة','Introduction to Programming',3,'college_required',33,true),
('2110139','أساسيات تكنولوجيا المعلومات','IT Fundamentals',3,'college_required',34,true),
('2110140','البحث العلمي والكتابة الفنية','Scientific Research and Technical Writing',3,'college_required',35,true),
('2110201','التحليل العددي','Numerical Analysis',3,'college_required',36,true),
('2110141','الرياضيات المتقطعة','Discrete Mathematics',3,'department_required',50,true),
('2312102','أساسيات علم البيانات','Data Science Fundamentals',2,'department_required',51,true),
('2312103','مختبر أساسيات علم البيانات','Data Science Fundamentals Lab',1,'department_required',52,true),
('2312201','أساسيات الذكاء الاصطناعي','AI Fundamentals',3,'department_required',53,true),
('2312206','استعراض البيانات','Data Visualization',3,'department_required',54,true),
('2312207','هندسة وتحليل البيانات','Data Engineering and Analysis',3,'department_required',55,true),
('2312211','الذكاء الاصطناعي المتقدم','Advanced Artificial Intelligence',2,'department_required',56,true),
('2312212','مختبر الذكاء الاصطناعي المتقدم','Advanced AI Lab',1,'department_required',57,true),
('2312301','التنقيب في البيانات واسترجاعها','Data Mining and Retrieval',3,'department_required',58,true),
('2312303','الأنظمة الخبيرة','Expert Systems',3,'department_required',59,true),
('2312305','برمجة الذكاء الاصطناعي','AI Programming',3,'department_required',60,true),
('2312308','الحوسبة السحابية والأنظمة الموزعة','Cloud Computing and Distributed Systems',3,'department_required',61,true),
('2312310','تصميم وتحليل الخوارزميات','Algorithm Design and Analysis',3,'department_required',62,true),
('2312311','قواعد البيانات','Databases',2,'department_required',63,true),
('2312312','مختبر قواعد البيانات','Databases Lab',1,'department_required',64,true),
('2312402','الشبكات العصبونية','Neural Networks',3,'department_required',65,true),
('2312404','تعلم الآلة','Machine Learning',3,'department_required',66,true),
('2312407','معالجة اللغات الطبيعية','Natural Language Processing',3,'department_required',67,true),
('2312408','التعرف على الأنماط','Pattern Recognition',3,'department_required',68,true),
('2312409','التعلم العميق','Deep Learning',3,'department_required',69,true),
('2312410','البيانات الكبيرة','Big Data',3,'department_required',70,true),
('2312411','تدريب عملي ميداني في الذكاء الاصطناعي','AI Field Training',3,'department_required',71,true),
('2312415','مشروع تخرج في الذكاء الاصطناعي (1)','AI Graduation Project (1)',1,'department_required',72,true),
('2312416','مشروع تخرج في الذكاء الاصطناعي (2)','AI Graduation Project (2)',2,'department_required',73,true),
('2321106','البرمجة الكينونية','Object-Oriented Programming',2,'department_required',74,true),
('2321107','مختبر البرمجة الكينونية','OOP Lab',1,'department_required',75,true),
('2321207','تراكيب البيانات','Data Structures',3,'department_required',76,true),
('2331307','أمن البيانات والمعلومات','Data and Information Security',3,'department_required',77,true),
('2331314','نظم التشغيل','Operating Systems',3,'department_required',78,true),
('2312204','الواقع الافتراضي','Virtual Reality',3,'department_elective',90,true),
('2312205','مبادئ وأخلاقيات الذكاء الاصطناعي','AI Ethics and Principles',3,'department_elective',91,true),
('2312302','إنترنت الأشياء','Internet of Things',3,'department_elective',92,true),
('2312306','موضوعات خاصة في الذكاء الاصطناعي (1)','Special Topics in AI (1)',3,'department_elective',93,true),
('2312307','تطبيقات الذكاء الاصطناعي في أمن المعلومات','AI Applications in InfoSec',3,'department_elective',94,true),
('2312401','الروبوتات','Robotics',3,'department_elective',95,true),
('2312403','أنظمة التوصية','Recommender Systems',3,'department_elective',96,true),
('2312406','موضوعات خاصة في الذكاء الاصطناعي (2)','Special Topics in AI (2)',3,'department_elective',97,true),
('2110101','عربي استدراكي','Remedial Arabic',3,'remedial',110,true),
('2110102','إنجليزي استدراكي','Remedial English',3,'remedial',111,true),
('2110103','حاسوب استدراكي','Remedial Computer',3,'remedial',112,true);
