INSERT INTO aut_courses (course_code, course_name_ar, course_name_en, credits, category, description_ar, display_order) VALUES
('2110104', 'مهارات الإتصال والتواصل باللغة العربية(1)', NULL, 2, 'university_required', NULL, 0),
('2110106', 'مهارات الإتصال والتواصل باللغة الإنجليزية(1)', NULL, 2, 'university_required', NULL, 1),
('2110108', 'التربية الوطنية', NULL, 2, 'university_required', NULL, 2),
('2110109', 'العلوم العسكرية', NULL, 3, 'university_required', NULL, 3),
('2110115', 'الريادة والإبتكار', NULL, 2, 'university_required', NULL, 4),
('2110117', 'القيادة والمسؤولية المجتمعية', NULL, 2, 'university_required', NULL, 5),
('2110120', 'مهارات حياتية', NULL, 2, 'university_required', NULL, 6),
('2110105', 'مهارات الإتصال والتواصل باللغة العربية(2)', NULL, 3, 'university_elective', NULL, 7),
('2110107', 'مهارات الإتصال والتواصل باللغة الإنجليزية(2)', NULL, 3, 'university_elective', NULL, 8),
('2110114', 'الحضارة الاسلامية', NULL, 3, 'university_elective', NULL, 9),
('2110118', 'تعلم التفكير المنطقي', NULL, 3, 'university_elective', NULL, 10),
('2110119', 'حقوق الملكية الفكرية', NULL, 3, 'university_elective', NULL, 11),
('2110110', 'الإسعافات الأولية والسلامة العامة', NULL, 3, 'university_elective', NULL, 12),
('2110112', 'التنمية والبيئة', NULL, 3, 'university_elective', NULL, 13),
('2110116', 'الغذاء والدواء(لغير طلبة كلية الصيدلة)', NULL, 3, 'university_elective', NULL, 14),
('2110111', 'التجارة الالكترونية(لغير طلبة كلية تكنولوجيا المعلومات)', NULL, 3, 'university_elective', NULL, 15),
('2110113', 'الثقافة الرقمية', NULL, 3, 'university_elective', NULL, 16),
('2110101', 'عربي إستدراكي', NULL, 0, 'remedial', NULL, 17),
('2110102', 'إنجليزي إستدراكي', NULL, 0, 'remedial', NULL, 18),
('2110103', 'حاسوب إستدراكي', NULL, 0, 'remedial', NULL, 19),
('2110121', 'الإحصاء والاحتمالات لطلبة تكنولوجيا المعلومات', NULL, 3, 'college_required', NULL, 20),
('2110122', 'التفاضل والتكامل (1)', NULL, 3, 'college_required', NULL, 21),
('2110201', 'التحليل العددي', NULL, 3, 'college_required', NULL, 22),
('2110138', 'مقدمة في البرمجة', 'Introduction to Programming', 3, 'college_required', NULL, 23),
('2110139', 'اساسيات تكنولوجيا المعلومات', NULL, 3, 'college_required', NULL, 24),
('2110137', 'اللغة الإنجليزية التخصصية لطلبة تكنولوجيا المعلومات ESP', 'ESP', 3, 'college_required', NULL, 25),
('2110140', 'البحث العلمي والكتابة الفنية', 'Scientific Research and Technical Writing', 3, 'college_required', NULL, 26),
('2312102', 'أساسيات علم البيانات', 'Fundamentals of Data Science', 2, 'department_required', NULL, 27),
('2312103', 'مختبر أساسيات علم البيانات', 'Fundamentals of Data Science Lab', 1, 'department_required', NULL, 28),
('2312201', 'أساسيات الذكاء الاصطناعي', 'Fundamentals of Artificial Intelligence', 3, 'department_required', NULL, 29),
('2312211', 'الذكاء الاصطناعي المتقدم', 'Advanced Artificial Intelligence', 2, 'department_required', NULL, 30),
('2312212', 'مختبر الذكاء الاصطناعي المتقدم', 'Advanced Artificial Intelligence Lab', 1, 'department_required', NULL, 31),
('2321207', 'تراكيب البيانات', 'Data Structures', 3, 'department_required', NULL, 32),
('2312207', 'هندسة و تحليل البيانات', 'Data Engineering and Analysis', 3, 'department_required', NULL, 33),
('2312301', 'التنقيب في البيانات واسترجاعها', 'Data Mining and Retrieval', 3, 'department_required', NULL, 34),
('2312303', 'الأنظمة الخبيرة', 'Expert Systems', 3, 'department_required', NULL, 35),
('2312305', 'برمجة الذكاء الاصطناعي', 'AI Programming', 3, 'department_required', NULL, 36),
('2312308', 'الحوسبة السحابية والأنظمة الموزعة', 'Cloud Computing and Distributed Systems', 3, 'department_required', NULL, 37),
('2312402', 'الشبكات العصبونية', 'Neural Networks', 3, 'department_required', NULL, 38),
('2312404', 'تعلم الآلة', 'Machine Learning', 3, 'department_required', NULL, 39),
('2312407', 'معالجة اللغات الطبيعية', 'Natural Language Processing', 3, 'department_required', NULL, 40),
('2312408', 'التعرف على الانماط', 'Pattern Recognition', 3, 'department_required', NULL, 41),
('2312411', 'تدريب عملي ميداني في الذكاء الاصطناعي', 'AI Field Training', 3, 'department_required', NULL, 42),
('2312409', 'التعلم العميق', 'Deep Learning', 3, 'department_required', NULL, 43),
('2312410', 'البيانات الكبيرة', 'Big Data', 3, 'department_required', NULL, 44),
('2312415', 'مشروع تخرج في الذكاء الاصطناعي (1)', 'AI Graduation Project 1', 1, 'department_required', NULL, 45),
('2312416', 'مشروع تخرج في الذكاء الاصطناعي (2)', 'AI Graduation Project 2', 2, 'department_required', NULL, 46),
('2321106', 'البرمجة الكينونية', 'Object Oriented Programming', 2, 'department_required', NULL, 47),
('2321107', 'مختبر البرمجة الكينونية', 'OOP Lab', 1, 'department_required', NULL, 48),
('2110141', 'الرياضيات المتقطعة', 'Discrete Mathematics', 3, 'college_required', NULL, 49),
('2312311', 'قواعد البيانات', 'Databases', 2, 'department_required', NULL, 50),
('2312312', 'مختبر قواعد البيانات', 'Databases Lab', 1, 'department_required', NULL, 51),
('2312310', 'تصميم وتحليل الخوارزميات', 'Design and Analysis of Algorithms', 3, 'department_required', NULL, 52),
('2331314', 'نظم التشغيل', 'Operating Systems', 3, 'department_required', NULL, 53),
('2331307', 'أمن البيانات والمعلومات', 'Data and Information Security', 3, 'department_required', NULL, 54),
('2312206', 'استعراض البيانات', 'Data Visualization', 3, 'department_required', NULL, 55),
('2321312', 'برمجة تطبيقات الانترنت', 'Web Application Programming', 3, 'department_required', NULL, 56),
('2312204', 'الواقع الافتراضي', 'Virtual Reality', 3, 'department_elective', NULL, 57),
('2312205', 'مبادئ وأخلاقيات الذكاء الاصطناعي', 'AI Principles and Ethics', 3, 'department_elective', NULL, 58),
('2312302', 'انترنت الاشياء', 'Internet of Things', 3, 'department_elective', NULL, 59),
('2312306', 'موضوعات خاصة في الذكاء الاصطناعي (1)', 'Special Topics in AI 1', 3, 'department_elective', NULL, 60),
('2312307', 'تطبيقات الذكاء الاصطناعي في امن المعلومات', 'AI Applications in Information Security', 3, 'department_elective', NULL, 61),
('2312401', 'الروبوتات', 'Robotics', 3, 'department_elective', NULL, 62),
('2312403', 'انظمة التوصية', 'Recommendation Systems', 3, 'department_elective', NULL, 63),
('2312406', 'موضوعات خاصة في الذكاء الاصطناعي (2)', 'Special Topics in AI 2', 3, 'department_elective', NULL, 64)
ON CONFLICT (course_code) DO UPDATE SET
  course_name_ar = EXCLUDED.course_name_ar,
  course_name_en = EXCLUDED.course_name_en,
  credits = EXCLUDED.credits,
  category = EXCLUDED.category,
  display_order = EXCLUDED.display_order,
  is_active = true;